environment:
    type: "MemoryGym"
    name: "Endless-MortarMayhem-v0"
    reset_params:
        start-seed: 0
        num-seeds: 10000
gamma: 0.995          
lamda: 0.95           
updates: 10000        
epochs: 3
n_workers: 16
worker_steps: 256
n_mini_batch: 8
value_loss_coefficient: 0.5
max_grad_norm: 0.25
hidden_layer_size: 512
recurrence:
    sequence_length: 512         
    hidden_state_size: 512
    layer_type: xlstm               
    reset_hidden_state: False
learning_rate_schedule:
    initial: 2.75e-4
    final:   1.0e-5
    power: 1.0
    max_decay_steps: 10000
beta_schedule:       
    initial: 1.0e-4
    final:   1.0e-6
    power: 1.0
    max_decay_steps: 10000
clip_range_schedule:
    initial: 0.1
    final:   0.1
    power: 1.0
    max_decay_steps: 10000

